name: Update CS Prices

on:
    schedule:
        - cron: "0 10 * * *"

    workflow_dispatch:

jobs:
    download:
        runs-on: ubuntu-latest

        permissions:
            contents: write

        steps:
            - uses: actions/checkout@master
            - uses: actions/setup-node@v3
            - name: Update CS2 prices
              run: npm install && node index.js '${{ secrets.USERNAME }}' '${{ secrets.PASSWORD }}'
            - name: Get current date and time
              id: current_datetime
              run: echo "CURRENT_DATETIME=$(date +'%Y-%m-%d %H:%M:%S')" >> $GITHUB_ENV
            - name: Commit & push changes
              uses: stefanzweifel/git-auto-commit-action@v4
              with:
                  commit_message: "Updated CS2 Prices - ${{ env.CURRENT_DATETIME }}"